// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWAy_227mQaNek9HZMlJM98itfSna1uls',
    appId: '1:929349489874:web:9ed6b13222b37eca2fc90b',
    messagingSenderId: '929349489874',
    projectId: 'helpera-9bef4',
    authDomain: 'helpera-9bef4.firebaseapp.com',
    storageBucket: 'helpera-9bef4.appspot.com',
    measurementId: 'G-FZJ82R9C26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZivrxQbf9T67eF2nAwwTK6c9Uqd5oUkI',
    appId: '1:929349489874:android:6b8f47b7ecb231fa2fc90b',
    messagingSenderId: '929349489874',
    projectId: 'helpera-9bef4',
    storageBucket: 'helpera-9bef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0WrPflbWiAHl9N5yJqFWeYrzwyAiLaKo',
    appId: '1:929349489874:ios:f8bbdb92a27076a52fc90b',
    messagingSenderId: '929349489874',
    projectId: 'helpera-9bef4',
    storageBucket: 'helpera-9bef4.appspot.com',
    iosClientId: '929349489874-6sps58evdpl3amevs9asscp2pphevgb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0WrPflbWiAHl9N5yJqFWeYrzwyAiLaKo',
    appId: '1:929349489874:ios:f8bbdb92a27076a52fc90b',
    messagingSenderId: '929349489874',
    projectId: 'helpera-9bef4',
    storageBucket: 'helpera-9bef4.appspot.com',
    iosClientId: '929349489874-6sps58evdpl3amevs9asscp2pphevgb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientApp',
  );
}
